// app/src/components/Login/Login.tsx
import React, { useState } from 'react';

export const Login: React.FC = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8 p-8 bg-white shadow rounded-lg">
        <h1 className="text-4xl font-bold text-center mb-8">FinanceMate</h1>
        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label htmlFor="email" className="block text-sm font-medium text-gray-700">
              Email
            </label>
            <input
              type="email"
              id="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 text-base text-gray-900"
            />
          </div>
          <div className="mb-4">
            <label htmlFor="password" className="block text-sm font-medium text-gray-700">
              Password
            </label>
            <input
              type="password"
              id="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 text-base text-gray-900"
            />
          </div>
          <div className="text-center">
            <button
              type="submit"
              className="inline-flex items-center px-4 py-2 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-pink-600 hover:bg-pink-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500"
            >
              Login
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// app/pages/auth/login.vue
<template>
    <div class="min-h-screen flex items-center justify-center">
      <div class="border w-full max-w-md p-8 space-y-6 bg-white rounded-lg shadow-md">
        <h2 class="text-center text-3xl font-bold text-gray-900">FinanceMate</h2>
        <h3 class="text-center text-xl font-semibold text-gray-700">Welcome</h3>
  
        <form class="space-y-6" @submit.prevent="submitForm">
          <div>
            <label for="email" class="sr-only">Email</label>
            <input
              type="email"
              id="email"
              v-model="email"
              placeholder="Email"
              required
              class="w-full px-4 py-2 text-gray-700 border border-gray-300 rounded-lg focus:border-blue-500 focus:ring-2 focus:ring-blue-500 focus:outline-none"
            />
          </div>
  
          <div>
            <label for="password" class="sr-only">Password</label>
            <input
              type="password"
              id="password"
              v-model="password"
              placeholder="Password"
              required
              class="w-full px-4 py-2 text-gray-700 border border-gray-300 rounded-lg focus:border-blue-500 focus:ring-2 focus:ring-blue-500 focus:outline-none"
            />
          </div>
  
          <div class="flex items-center justify-between">
            <label for="remember_me" class="flex items-center">
              <input
                type="checkbox"
                id="remember_me"
                class="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
              />
              <span class="ml-2 text-sm text-gray-600">Remember me</span>
            </label>
  
            <a href="#" class="text-sm text-blue-600 hover:text-blue-500">Forgot password?</a>
          </div>
  
          <button
            type="submit"
            class="w-full px-4 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-700 focus:outline-none"
          >
            Login
          </button>
        </form>
  
        <div class="text-center">
          <span class="text-sm text-gray-600">No accounts yet?</span>
          <nuxt-link to="/register" class="ml-1 text-sm text-blue-600 hover:text-blue-500">
              Register
            </nuxt-link>
        </div>
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref } from 'vue';
  
  const email = ref('');
  const password = ref('');
  
  function submitForm() {
    console.log('Email:', email.value);
    console.log('Password:', password.value);
  }
  </script>
  
  <style scoped>
  </style>
